/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiWellnessGuideRouteImport } from './routes/ai-wellness-guide'
import { Route as AnxietyDisordersRouteImport } from './routes/anxiety-disorders'
import { Route as BehavioralAnalyticsRouteImport } from './routes/behavioral-analytics'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgressTrackerRouteImport } from './routes/progress-tracker'
import { Route as RecoveryJourneyRouteImport } from './routes/recovery-journey'
import { Route as ResearchCenterRouteImport } from './routes/research-center'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UnderstandingAnxietyRouteImport } from './routes/understanding-anxiety'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWellnessGuideRoute = AiWellnessGuideRouteImport.update({
  id: '/ai-wellness-guide',
  path: '/ai-wellness-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AnxietyDisordersRoute = AnxietyDisordersRouteImport.update({
  id: '/anxiety-disorders',
  path: '/anxiety-disorders',
  getParentRoute: () => rootRouteImport,
} as any)
const BehavioralAnalyticsRoute = BehavioralAnalyticsRouteImport.update({
  id: '/behavioral-analytics',
  path: '/behavioral-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressTrackerRoute = ProgressTrackerRouteImport.update({
  id: '/progress-tracker',
  path: '/progress-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryJourneyRoute = RecoveryJourneyRouteImport.update({
  id: '/recovery-journey',
  path: '/recovery-journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchCenterRoute = ResearchCenterRouteImport.update({
  id: '/research-center',
  path: '/research-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UnderstandingAnxietyRoute = UnderstandingAnxietyRouteImport.update({
  id: '/understanding-anxiety',
  path: '/understanding-anxiety',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-wellness-guide': typeof AiWellnessGuideRoute
  '/anxiety-disorders': typeof AnxietyDisordersRoute
  '/behavioral-analytics': typeof BehavioralAnalyticsRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/progress-tracker': typeof ProgressTrackerRoute
  '/recovery-journey': typeof RecoveryJourneyRoute
  '/research-center': typeof ResearchCenterRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/understanding-anxiety': typeof UnderstandingAnxietyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-wellness-guide': typeof AiWellnessGuideRoute
  '/anxiety-disorders': typeof AnxietyDisordersRoute
  '/behavioral-analytics': typeof BehavioralAnalyticsRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/progress-tracker': typeof ProgressTrackerRoute
  '/recovery-journey': typeof RecoveryJourneyRoute
  '/research-center': typeof ResearchCenterRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/understanding-anxiety': typeof UnderstandingAnxietyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-wellness-guide': typeof AiWellnessGuideRoute
  '/anxiety-disorders': typeof AnxietyDisordersRoute
  '/behavioral-analytics': typeof BehavioralAnalyticsRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/progress-tracker': typeof ProgressTrackerRoute
  '/recovery-journey': typeof RecoveryJourneyRoute
  '/research-center': typeof ResearchCenterRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/understanding-anxiety': typeof UnderstandingAnxietyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-wellness-guide'
    | '/anxiety-disorders'
    | '/behavioral-analytics'
    | '/case-studies'
    | '/contact'
    | '/privacy'
    | '/progress-tracker'
    | '/recovery-journey'
    | '/research-center'
    | '/resources'
    | '/terms'
    | '/understanding-anxiety'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-wellness-guide'
    | '/anxiety-disorders'
    | '/behavioral-analytics'
    | '/case-studies'
    | '/contact'
    | '/privacy'
    | '/progress-tracker'
    | '/recovery-journey'
    | '/research-center'
    | '/resources'
    | '/terms'
    | '/understanding-anxiety'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-wellness-guide'
    | '/anxiety-disorders'
    | '/behavioral-analytics'
    | '/case-studies'
    | '/contact'
    | '/privacy'
    | '/progress-tracker'
    | '/recovery-journey'
    | '/research-center'
    | '/resources'
    | '/terms'
    | '/understanding-anxiety'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiWellnessGuideRoute: typeof AiWellnessGuideRoute
  AnxietyDisordersRoute: typeof AnxietyDisordersRoute
  BehavioralAnalyticsRoute: typeof BehavioralAnalyticsRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgressTrackerRoute: typeof ProgressTrackerRoute
  RecoveryJourneyRoute: typeof RecoveryJourneyRoute
  ResearchCenterRoute: typeof ResearchCenterRoute
  ResourcesRoute: typeof ResourcesRoute
  TermsRoute: typeof TermsRoute
  UnderstandingAnxietyRoute: typeof UnderstandingAnxietyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-wellness-guide': {
      id: '/ai-wellness-guide'
      path: '/ai-wellness-guide'
      fullPath: '/ai-wellness-guide'
      preLoaderRoute: typeof AiWellnessGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anxiety-disorders': {
      id: '/anxiety-disorders'
      path: '/anxiety-disorders'
      fullPath: '/anxiety-disorders'
      preLoaderRoute: typeof AnxietyDisordersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behavioral-analytics': {
      id: '/behavioral-analytics'
      path: '/behavioral-analytics'
      fullPath: '/behavioral-analytics'
      preLoaderRoute: typeof BehavioralAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress-tracker': {
      id: '/progress-tracker'
      path: '/progress-tracker'
      fullPath: '/progress-tracker'
      preLoaderRoute: typeof ProgressTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-journey': {
      id: '/recovery-journey'
      path: '/recovery-journey'
      fullPath: '/recovery-journey'
      preLoaderRoute: typeof RecoveryJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-center': {
      id: '/research-center'
      path: '/research-center'
      fullPath: '/research-center'
      preLoaderRoute: typeof ResearchCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/understanding-anxiety': {
      id: '/understanding-anxiety'
      path: '/understanding-anxiety'
      fullPath: '/understanding-anxiety'
      preLoaderRoute: typeof UnderstandingAnxietyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiWellnessGuideRoute: AiWellnessGuideRoute,
  AnxietyDisordersRoute: AnxietyDisordersRoute,
  BehavioralAnalyticsRoute: BehavioralAnalyticsRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ProgressTrackerRoute: ProgressTrackerRoute,
  RecoveryJourneyRoute: RecoveryJourneyRoute,
  ResearchCenterRoute: ResearchCenterRoute,
  ResourcesRoute: ResourcesRoute,
  TermsRoute: TermsRoute,
  UnderstandingAnxietyRoute: UnderstandingAnxietyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
